server:
  port: 8090

# Application information
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: abhinath-dev-backend
  devtools:
    restart:
      enabled: true
