jwt:
  secret: sadadadsfsdrd5rfgvgshdcqd3232dsa

spring:
  datasource:
    url: jdbc:h2:./test/test;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER:jabhinath1995@gmail.com}
    password: ${EMAIL_PASSWORD:test}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true