server:
#  ssl:
#    enabled: true
#    key-store: classpath:abhinathdev.p12   # Path to your .p12 file
#    key-store-password: Rangrover          # Password for the .p12 file
#    key-store-type: PKCS12                 # Keystore type is PKCS12
#    key-alias: abbhinath-dev               # The alias of your key
#    key-password: Rangrover                # The password for the private key (optional if the same as key-store-password)
  port: 8080


# Application information
spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: abhinath-dev-backend
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  devtools:
    restart:
      enabled: true


#logging:
#  level:
#    org.springframework.security: DEBUG


jwt:
  secret: ${JWT_SECRET}