name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
    paths:
      - 'akasa-react/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'akasa-react/**'

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('akasa-react/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: ./akasa-react

      - name: Build the application
        run: npm run build
        working-directory: ./akasa-react

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./akasa-react
          file: ./akasa-react/Dockerfile
          push: true
          tags: nuline/akasa-react:latest
